import { GoogleGenAI } from "@google/genai";
import { NextResponse } from "next/server";

const ai = new GoogleGenAI({ apiKey: process.env.GOOGLE_GEMINI_API_KEY! });

export async function POST(req: Request) {
  try {
    const { country, days, travelStyle, budgetLevel } = await req.json();

    const prompt = `
You are an expert travel planner. Generate a detailed, realistic JSON itinerary for:
- Country/Destination: ${country}
- Duration: ${days} days
- Travel Style: ${travelStyle}
- Budget Level: ${budgetLevel}

IMPORTANT REQUIREMENTS:
1. Return ONLY valid JSON. No markdown, no explanations, no code blocks.
2. Generate exactly ${days} days of activities.
3. Each day should have 3-5 activities that are realistic and well-timed.
4. Use REAL coordinates (latitude/longitude) for actual places in ${country}.
5. Activities should be logically ordered by location and time.
6. Travel times between activities should be realistic (considering distance and transportation).
7. Times should be in 24-hour format (HH:MM) and span a full day (e.g., 09:00, 12:00, 15:00, 18:00).
8. Estimated costs should reflect the ${budgetLevel} budget level:
   - Budget: $5-$30 per activity
   - Moderate: $20-$80 per activity
   - Luxury: $50-$200+ per activity
9. Include a mix of: attractions, restaurants, cultural sites, scenic spots, and local experiences.
10. Cities should be actual cities/towns in ${country}.
11. Activities should match the ${travelStyle} travel style.

Return valid JSON in this exact format:
{
  "days": [
    {
      "day": 1,
      "city": "ActualCityName",
      "activities": [
        {
          "name": "Real Place or Activity Name",
          "description": "Detailed 2-3 sentence description of what to expect, why it's worth visiting, and what makes it special",
          "lat": 35.6762,
          "lng": 139.6503,
          "time": "09:00",
          "estimatedCost": 25,
          "travelTimeMinutes": 0
        }
      ]
    }
  ]
}
`;

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash-lite", // Ensure you use a valid model name
      contents: [
        {
          role: "user",
          parts: [
            { text: prompt }
          ]
        }
      ],
      // OPTIONAL: This forces the model to return JSON, reducing parse errors
      config: {
        responseMimeType: "application/json",
      }
    });

    // 1. Check if text exists
    const text = response.text;
    if (!text) {
      return NextResponse.json({ error: "No text generated by AI" }, { status: 500 });
    }

    // 2. Parse the validated string
    let json;
    try {
      json = JSON.parse(text);
    } catch {
      return NextResponse.json({ error: "Invalid JSON from AI", raw: text }, { status: 500 });
    }

    // 3. Return the successful response
    return NextResponse.json(json);

  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}