import { GoogleGenAI } from "@google/genai";
import { NextResponse } from "next/server";

const ai = new GoogleGenAI({ apiKey: process.env.GOOGLE_GEMINI_API_KEY! });

export async function POST(req: Request) {
  try {
    const { country, day, travelStyle, budgetLevel, currentCities } = await req.json();

    const currentCitiesList = currentCities && currentCities.length > 0 
      ? `Avoid these cities already in the itinerary: ${currentCities.join(", ")}. ` 
      : "";

    const prompt = `
You are an expert travel planner. Generate a new city/location for a day in an itinerary:
- Country: ${country}
- Day: ${day}
- Travel Style: ${travelStyle}
- Budget Level: ${budgetLevel}
${currentCitiesList}
IMPORTANT REQUIREMENTS:
1. Return ONLY valid JSON. No markdown, no explanations, no code blocks.
2. Suggest a REAL city or town in ${country} that is worth visiting.
3. The city should be different from typical tourist destinations - suggest something interesting and unique.
4. The city should match the ${travelStyle} travel style.
5. Consider the ${budgetLevel} budget level when suggesting the city.
6. Make sure the city is accessible and has interesting attractions/activities.

Return valid JSON in this exact format:
{
  "city": "CityName"
}
`;

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash-lite",
      contents: [
        {
          role: "user",
          parts: [
            { text: prompt }
          ]
        }
      ],
      config: {
        responseMimeType: "application/json",
      }
    });

    const text = response.text;
    if (!text) {
      return NextResponse.json({ error: "No text generated by AI" }, { status: 500 });
    }

    let json;
    try {
      json = JSON.parse(text);
    } catch {
      return NextResponse.json({ error: "Invalid JSON from AI", raw: text }, { status: 500 });
    }

    return NextResponse.json(json);

  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}

