import { GoogleGenAI } from "@google/genai";
import { NextResponse } from "next/server";

const ai = new GoogleGenAI({ apiKey: process.env.GOOGLE_GEMINI_API_KEY! });

export async function POST(req: Request) {
  try {
    const { country, city, day, time, travelStyle, budgetLevel } = await req.json();

    const prompt = `
You are an expert travel planner. Generate a single activity/location for:
- Country: ${country}
- City: ${city}
- Day: ${day}
- Time slot: ${time}
- Travel Style: ${travelStyle}
- Budget Level: ${budgetLevel}

IMPORTANT REQUIREMENTS:
1. Return ONLY valid JSON. No markdown, no explanations, no code blocks.
2. Generate ONE activity that fits the time slot and location.
3. Use REAL coordinates (latitude/longitude) for an actual place in ${city}, ${country}.
4. Estimated cost should reflect the ${budgetLevel} budget level:
   - Budget: $5-$30
   - Moderate: $20-$80
   - Luxury: $50-$200+
5. The activity should match the ${travelStyle} travel style.
6. Make it different from typical tourist spots - suggest something interesting and unique.
7. Description should be 2-3 sentences explaining what to expect and why it's worth visiting.

Return valid JSON in this exact format:
{
  "name": "Activity or Place Name",
  "description": "Detailed 2-3 sentence description",
  "lat": 35.6762,
  "lng": 139.6503,
  "time": "${time}",
  "estimatedCost": 25,
  "travelTimeMinutes": 0
}
`;

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash-lite",
      contents: [
        {
          role: "user",
          parts: [
            { text: prompt }
          ]
        }
      ],
      config: {
        responseMimeType: "application/json",
      }
    });

    const text = response.text;
    if (!text) {
      return NextResponse.json({ error: "No text generated by AI" }, { status: 500 });
    }

    let json;
    try {
      json = JSON.parse(text);
    } catch {
      return NextResponse.json({ error: "Invalid JSON from AI", raw: text }, { status: 500 });
    }

    return NextResponse.json(json);

  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}

